platform :ios, '11.0'
use_frameworks!

workspace 'Sample'
project 'Sample'

GNCORE='https://gitlab.com/gncore/specs.git'

target 'Sample' do
    pod 'NInject', :path => './../'

    target 'SampleTests' do
        inherit! :search_paths

        pod 'NInjectTestHelpers', :path => './../', :testspecs => ['Tests']
    end
end
